parameters:
services:
  _defaults:
    autoconfigure: true

  App\Controller\IndexController:
    calls:
      - [ 'setContainer', [ '@service_container' ] ]
    arguments:
      - '@Twig_Environment'