version: '3.8'

services:
  php-fpm:
    build: docker/php-fpm
    container_name: mini-cms-php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app:cached
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - mini_cms_backend_net

  nginx:
    build: docker/nginx
    ports:
      - "8080:80"
    volumes:
      - .:/app:cached
      - ./docker/nginx/dev-nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/dev-default.conf:/etc/nginx/sites-available/default.conf
      - ./docker/nginx/conf.d/dev-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - mini_cms_backend_net

  mysql:
    build: docker/mysql
    container_name: mini-cms-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - "9018:3306"
    volumes:
      - ./docker/volumes/mariadb:/var/lib/mysql
    networks:
      - mini_cms_backend_net

networks:
  mini_cms_backend_net: