parameters:
services:
  _defaults:
    autoconfigure: true

  App\Api\Content\Controller\ContentController:
    calls:
      - [ 'setContainer', [ '@service_container' ] ]
    arguments:
      - '@content.repository'
      - '@App\Api\Response\JsonResponseType'
      - 'App\Entity\ContentEntity'