name: CI

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: PHPStan Analysis
        uses: php-actions/phpstan@v3
        with:
          php_version: 8.2
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          fetch-depth: 0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - name: Run PHP_CodeSniffer
        run: |
          ./vendor/bin/phpstan --memory-limit=1G

  php_security_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: PHP Security Checker
        run: |
          curl --location --output local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.6/local-php-security-checker_2.0.6_linux_amd64
          echo '314309702970bd8f2eed68301c3c42012a938fb8ae5c977c4ab0db57bb69b23c  local-php-security-checker' > local-php-security-checker.sha256
          sha256sum --check local-php-security-checker.sha256
          chmod +x local-php-security-checker
          ./local-php-security-checker
  
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Start container
        run: docker-compose up mysql

      - name: Run test
        run: |
          cd Golang
          make test

      - name: Stop container
        if: always()
        run: docker-compose down mysql